//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookDescription { get; set; }
        public int BookGenreID { get; set; }
        public int ProviderID { get; set; }
        public int PublishingHouseID { get; set; }
        public int AuthorID { get; set; }
        public string BookISBN { get; set; }
        public int BookCount { get; set; }
        public int BookPrice { get; set; }
        public string BookImage { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookGenre BookGenre { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
